
# Description: Docker compose to bring up environment for API
# Author: neatMon, Inc.
# License: MIT

version: "3.8"
services:
    mongoDB:
        # https://hub.docker.com/_/mongo
        container_name: mongoDB
        hostname: mongo-database
        image: mongo
        volumes:
            - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
            - MONGO_INITDB_DATABASE=${MONGO_DATABASE_NAME}
        command: mongod
        restart: always
    neatmon-api:
        container_name: api
        hostname: api-server
        volumes:
            - "./server:/usr/src/app"
        build: ./server
        ports:
            - "1330:5000"
        environment:
            - MONGO_DATABASE_URI=${MONGO_DATABASE_URI}
            - MONGO_DATABASE_COLLECTION_DATA=${MONGO_DATABASE_COLLECTION_DATA}
            - MONGO_DATABASE_COLLECTION_CONFIGURATION=${MONGO_DATABASE_COLLECTION_CONFIGURATION}
            - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
            - MONGO_DATABASE_EDITOR_USER=${MONGO_DATABASE_EDITOR_USER}
            - MONGO_DATABASE_EDITOR_PASSWORD=${MONGO_DATABASE_EDITOR_PASSWORD}
            # - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            # - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        restart: always
        depends_on:
            - "mongoDB"